""" Adding logo column to Orgs

Revision ID: 73c104502e9
Revises: 1648101c5ff7
Create Date: 2015-05-20 17:23:17.519133

"""

# revision identifiers, used by Alembic.
revision = '73c104502e9'
down_revision = '1648101c5ff7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('logo', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'logo')
    ### end Alembic commands ###
